const { createApp } = Vue;

createApp({
    data() {
        return {
            companyName: '',
            industry: '',
            companySize: '',
            loading: false,
            analysisResults: [],
            uploadedFiles: []
        }
    },
    methods: {
        handleFileUpload(event) {
            this.uploadedFiles = Array.from(event.target.files);
        },

        async submitAnalysis() {
            if (!this.companyName || !this.industry || !this.companySize) {
                alert('Please fill in all required fields');
                return;
            }

            this.loading = true;
            try {
                const response = await fetch('https://r0c8kgwocscg8gsokogwwsw4.zetaverse.one/ai', {
                    method: 'POST',
                    headers: {
                        'Authorization': 'Bearer OBu8mNUDybQGnxSxQdqnsGY9IbR2',
                        'Content-Type': 'application/json'
                    },
                    body: JSON.stringify({
                        messages: [{
                            role: 'user',
                            content: [{
                                type: 'text',
                                text: `Generate a detailed AI implementation analysis for ${this.companyName}, a ${this.companySize} company in the ${this.industry} industry. Focus on competitive advantages, ROI potential, and strategic recommendations. Present the information in a narrative format without bullets or lists.`
                            }]
                        }]
                    })
                });

                const data = await response.json();
                const sections = data.message.split('\n\n').filter(section => section.trim());
                
                this.analysisResults = sections.map((section, index) => ({
                    title: ['Strategic Analysis', 'Implementation Strategy', 'ROI Projection'][index] || 'Additional Insights',
                    description: section.trim()
                }));
            } catch (error) {
                console.error('Error:', error);
                alert('An error occurred while generating recommendations');
            } finally {
                this.loading = false;
            }
        },

        async downloadResult(result) {
            const element = document.createElement('div');
            element.className = 'neumorphic p-6 bg-white';
            element.innerHTML = `
                <h2 class="text-2xl font-bold mb-4">${result.title}</h2>
                <p class="text-gray-700">${result.description}</p>
                <div class="mt-4 text-sm text-gray-500">
                    Generated by AI Accelerator Hub for ${this.companyName}
                    <br>
                    ${new Date().toLocaleDateString()}
                </div>
            `;
            document.body.appendChild(element);

            try {
                const canvas = await html2canvas(element);
                const link = document.createElement('a');
                link.download = `AI_Analysis_${Date.now()}.png`;
                link.href = canvas.toDataURL('image/png');
                link.click();
            } finally {
                document.body.removeChild(element);
            }
        },

        shareResult(result) {
            if (navigator.share) {
                navigator.share({
                    title: result.title,
                    text: result.description,
                    url: window.location.href
                }).catch(console.error);
            } else {
                alert('Sharing is not supported on this browser');
            }
        }
    }
}).mount('#app');